title: Shiken Chen's Homepage
page-top-title: Shiken Chen
top-section-bg-text: Economics
home-subtitle: Shiken Chen&ensp;|&ensp;陈子健
copyright-text: '&copy; Shiken Chen 2023-2025. All Rights Reserved.'
